# create the service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev2
  namespace: dev2
---
# create the role to grant access to configmaps
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev2
  name: role-api-readerdev2
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods","configmaps"]
    verbs: ["get", "watch", "list"]
---
# bind the role and the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-api-readerdev2
  namespace: ns-bswen
subjects:
  - kind: ServiceAccount
    name: dev2 # Name is case sensitive
    namespace: dev2
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: role-api-readerdev2 # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io