spring:
  application:
    name: configmap-oldversionpoc
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health,env,beans
  security:
    enabled: false
